---
dashboard_enabled: false

helm_enabled: true

registry_enabled: false

metrics_server_enabled: false

local_path_provisioner_enabled: false

local_volume_provisioner_enabled: false

csi_snapshot_controller_enabled: false

gateway_api_enabled: true

ingress_nginx_enabled: false
ingress_publish_status_address: ""

ingress_alb_enabled: false

cert_manager_enabled: true
cert_manager_namespace: "cert-manager"

metallb_enabled: false
metallb_speaker_enabled: "{{ metallb_enabled }}"
metallb_namespace: "metallb-system"

argocd_enabled: true
argocd_namespace: argocd

kube_vip_enabled: false

node_feature_discovery_enabled: false
