---
dashboard_enabled: false

helm_enabled: true

registry_enabled: false

metrics_server_enabled: true

local_path_provisioner_enabled: false

local_volume_provisioner_enabled: false

csi_snapshot_controller_enabled: false

gateway_api_enabled: true

ingress_nginx_enabled: false

ingress_alb_enabled: false

cert_manager_enabled: false

metallb_enabled: false

argocd_enabled: false

kube_vip_enabled: false

node_feature_discovery_enabled: false
