apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - storageclass.yaml

helmCharts:
  - name: csi-driver-smb
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    version: 1.19.1
    releaseName: csi-driver-smb
    namespace: kube-system
