# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - registry-key.yaml
  - network/certificate.yaml
  - network/destination-rule.yaml
  - network/gateway.yaml
  - network/service-entry.yaml
  - network/virtual-service.yaml
  - lgtm-stack/lgtm-stack.yaml
  - lgtm-stack/lgtm-stack-pvc.yaml
  - postgres/cnpg.yaml
  - redis/redis-pvc.yaml
  - redis/redis-service.yaml
  - redis/redis-stateful-set.yaml
  - server/server-deployment.yaml
  - server/server-svc.yaml
  - client/client-deployment.yaml
  - client/client-svc.yaml

configMapGenerator:
  - name: nixcn-cms-test-config
    namespace: nixcn-cms-test
    envs:
      - config.env
