# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - network/certificate.yaml
  - network/gateway.yaml
  - network/virtual-service.yaml
  - network/service-entry.yaml
  - network/destination-rule.yaml

patches:
  - path: patches/harbor-jobservice.yaml

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    version: 1.18.1
    releaseName: harbor
    namespace: harbor
    includeCRDs: false
    valuesFile: values.yaml
